services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://root:example@mongo_db:27017/text_analyzer_db?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=text-analyzer
      - KEYCLOAK_CLIENT_ID=backend-client
      - KEYCLOAK_CLIENT_SECRET=TZmo4EhwYBnfR0ZWfZxWALeAyimG1eVN
    networks:
      - text-analyzer-net
    depends_on:
      - redis
      - mongo_db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - text-analyzer-net
    volumes:
      - redis_data:/data

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=text_analyzer_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - text-analyzer-net
    volumes:
      - mongo_data:/data/db

  loki:
    image: grafana/loki:2.9.2
    ports:
      - '3100:3100'
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8080:8080'
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  text-analyzer-net:
    driver: bridge

volumes:
  redis_data:
  mongo_data:
  loki_data:
  grafana_data:
  postgres_data: