server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_grafana_loki_logging]
        target_label: __service__
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_label_com_grafana_loki_logging]
        action: keep
        regex: promtail
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: msg
            userId: userId
            textId: textId
            wordCount: wordCount
            characterCount: characterCount
            sentenceCount: sentenceCount
            paragraphCount: paragraphCount
            longestWords: longestWords
      - labels:
          level:
          userId:
          textId: